const catalogoProductos = [
{ id: 'CATUNSG16', name: "CACHANTUN 1.6 LT DESECHABLE x 6 unidades", price: 5520, category: "AGUA", image: "catalogo productos/catalogoactual/pack cachantun.webp", flavors: ["CON GAS", "SIN GAS", "STRONG GAS", "LIGTH GAS"] },
{ id: 'CATUNSG25', name: "CACHANTUN 2.5LT DESECHABLE x 6 unidades", price: 6540, category: "AGUA", image: "catalogo productos/catalogoactual/pack agua 2.5.webp", flavors: ["CON GAS", "SIN GAS"] },
{ id: 'CATUNSG5', name: "CACHANTUN 500ML x 12 unidades", price: 4000, category: "AGUA", image: "catalogo productos/catalogoactual/pack agua 500ml.webp", flavors: ["CON GAS", "SIN GAS", "STRONG GAS", "LIGTH GAS"] },
{ id: 'CCU600', name: "CCU 600ML DESECHABLE x 12 unidades", price: 10200, category: "BEBIDAS", image: "catalogo productos/catalogoactual/ccu600pack2.webp", flavors: ["PEPSI", "PESI ZERO", "KEM", "BILZ", "LIMON SODA", "GINGER", "CRUSH", "PAP"] },
{ id: 'EXPRB', name: "EXPRESS CCU X30", price: 11200, category: "BEBIDAS", image: "catalogo productos/catalogoactual/ccuexprespack3 (1).jpg", flavors: ["PEPSI", "PESI ZERO", "KEM", "BILZ", "LIMON SODA", "PAP"] },
{ id: 'GATO1A', name: "GATORADE 1LT DESECHABLE x 6 unidades", price: 7260, category: "BEBIDAS", image: "catalogo productos/catalogoactual/gatorate pack 4.jpg", flavors: ["AZUL", "ROJO", "NARANJA"] },
{ id: 'GATO750', name: "GATORADE 750ML x 6 unidades", price: 5280, category: "BEBIDAS", image: "catalogo productos/catalogoactual/gatorate750pack5.jpg", flavors: ["AZUL", "ROJO", "NARANJA"] },
{ id: 'L125', name: "CCU 1.25LT RETORNABLE x 12 unidades", price: 12990, category: "BEBIDAS", image: "catalogo productos/catalogoactual/ccu1.25pack6.jpg", flavors: ["´PAP", "BILZ", "KEM", "LIMON", "PEPSI", "PEPSI ZERO"] },
{ id: 'L2', name: "CCU 2LT RETORNABLE x 9 unidades", price: 13545, category: "BEBIDAS", image: "catalogo productos/catalogoactual/ccu2.5pack.png", flavors: ["´PAP", "BILZ", "KEM", "LIMON", "PEPSI", "PEPSI ZERO"] },
{ id: 'L25', name: "CCU 2.5 LT RETORNABLE x 6 unidades", price: 9498, category: "BEBIDAS", image: "catalogo productos/catalogoactual/Designer (1).jpg", flavors: ["´PAP", "BILZ", "KEM", "LIMON", "PEPSI", "PEPSI ZERO", "GINGER", "CRUSH"] },
{ id: 'L3', name: "CCU 3LT DESECHABLE x 6 unidades", price: 12080, category: "BEBIDAS", image: "catalogo productos/catalogoactual/ccu3.0pack.png", flavors: ["´PAP", "BILZ", "KEM", "LIMON", "PEPSI", "PEPSI ZERO", "GINGER", "CRUSH", "SEVEN UP"] },
{ id: 'LATAK6', name: "LATA CCU X 6 UNIDAD.", price: 3780, category: "BEBIDAS", image: "catalogo productos/catalogoactual/ccu lata pack.png", flavors: ["´PAP", "BILZ", "KEM", "LIMON", "PEPSI", "PEPSI ZERO", "GINGER", "CRUSH", "SEVEN UP", "KEM EXTREME"] },
{ id: 'LIPT15', name: "TE LIPTON 1.5 LT DESECHABLE x 6 unidades", price: 11526, category: "BEBIDAS", image: "catalogo productos/catalogoactual/lipton1.5pack.jpg", flavors: ["LIMON", "DURAZNO", "FRAMBUESA", "TE VERDE MANGO", "TE VERDE LIMON"] },
{ id: 'MASC', name: "AGUA MAS 600ML X12 UNID", price: 10516, category: "AGUA", image: "catalogo productos/catalogoactual/mas600pack.webp", flavors: ["UVA SIN GAS", "MANZANASIN GAS", "PERA SIN GAS", "GRANADA SIN GAS", "MANGO MARACUYA SIN GAS", "CITRUS CON GAS", "FRUTOS DEL BOSUQE CON GAS", "LIMONADA FRAMBUESA"] },
{ id: 'MASP', name: "CACHANTUN MAS 1.6 LT DESECHABLE x 6 unidades", price: 7521, category: "AGUA", image: "catalogo productos/catalogoactual/cacmas1.5pack.jpg", flavors: ["UVA SIN GAS", "MANZANASIN GAS", "PERA SIN GAS", "GRANADA SIN GAS", "MANGO MARACUYA SIN GAS", "CITRUS CON GAS", "FRUTOS DEL BOSUQE CON GAS", "LIMONADA FRAMBUESA"] },
{ id: 'RB250', name: "REDBULL 250ML x12 unid", price: 15200, category: "BEBIDAS", image: "catalogo/REDBULL 250ML x12 unid.avif", flavors: ["ORIGINAL"] },
{ id: 'RB355', name: "RED BULL 355CC X 12 UNIDADES", price: 20760, category: "ENERGÃ‰TICAS", image: "catalogo/RED BULL 355CC X 12 UNIDADES.avif", flavors: ["ORIGINAL"] },
{ id: 'RB473', name: "RED BULL 473CC X 12 UNIDADES", price: 25920, category: "ENERGÃ‰TICAS", image: "catalogo/RED BULL 473CC X 12 UNIDADES.avif", flavors: ["ORIGINAL"] },
{ id: 'RSTAR', name: "ROCKSTAR 500 ML x 12 unidades", price: 11160, category: "BEBIDAS", image: "catalogo/ROCKSTAR 500 ML.webp", flavors: ["ORIGINAL", "MANGO POWER", "SANDIA PUNSH"] },
{ id: 'WATTSD', name: "WATTS 1.5LT DESECHABLE x 6 unidades", price: 9120, category: "BEBIDAS", image: "catalogo productos/catalogoactual/watts1.5pack.webp", flavors: ["DURAZNO", "NARANJA", "PIÑA", "DURAZNO CERO", "NARANJA ZERO", "PIÑA ZERO", "TUTIFRUTILLA ORIGINAL", "TUTIFRUTILLA ZERO", "NARANJA MANZANA", "MANGO ZERO", "MARACUYA ZERO", "NARANJA PLATANO", "TUTIKIWI", "TUTIARANDANO", "DAMASCO", "MANZANA"] },
{ id: 'WB300', name: "WATTS BOCA ANCHA 300 ML x 24 unidades", price: 19920, category: "BEBIDAS", image: "catalogo productos/catalogoactual/bocaanchapack.jpg", flavors: ["DURAZNO", "NARANJA", "PIÑA", "TUTIFRUTILLA"] },
{ id: 'AND125', name: "COCA COLA 125 RETORNABLE x 10 unidades", price: 10250, category: "BEBIDAS", image: "catalogo productos/catalogoactual/cocacola1.25pack.webp", flavors: ["COCA COLA", "COCA COLA ZERO", "FANTA", "SPRITE", "INCA COLA"] },
{ id: 'AND15DES', name: "COCA COLA 1.5 LT DESECHABLE x 6 unidades", price: 9888, category: "BEBIDAS", image: "catalogo productos/catalogoactual/cocacola1.5pack.jpg", flavors: ["COCA COLA", "COCA COLA ZERO", "FANTA", "SPRITE", "INCA COLA"] },
{ id: 'AND2', name: "COCA COLA 2LT RETORNABLE x 8 unidades", price: 11880, category: "BEBIDAS", image: "catalogo productos/catalogoactual/cocacoal3.oretor.png", flavors: ["COCA COLA", "COCA COLA ZERO", "FANTA", "SPRITE", "INCA COLA", "SPRITE ZERO"] },
{ id: 'AND3', name: "COCA COLA 3LT RETORNABLE x 6 unidades", price: 12642, category: "BEBIDAS", image: "catalogo productos/catalogoactual/cocacoal3.oretor.png", flavors: ["COCA COLA", "COCA COLA ZERO", "FANTA", "SPRITE"] },
{ id: 'AND3DES', name: "COCA COLA 3LT DESECHABLE x 6 unidades", price: 14850, category: "BEBIDAS", image: "catalogo productos/catalogoactual/pack3ltcocacola.webp", flavors: ["COCA COLA", "COCA COLA ZERO", "FANTA", "SPRITE", "INCA COLA"] },
{ id: 'AND400', name: "ANDINA DEL VALLE 400ML x 6 unidades", price: 5040, category: "BEBIDAS", image: "catalogo productos/catalogoactual/andina400mlpack.jpg", flavors: ["DURAZNO", "NARANJA", "PIÑA", "TUTIFRUTILLA"] },
{ id: 'AND591', name: "COCA COLA 591ML DESECHABLE x 6 unidades", price: 5760, category: "BEBIDAS", image: "catalogo productos/catalogoactual/pack coca 591.jpg", flavors: ["COCA COLA", "COCA COLA ZERO", "FANTA", "SPRITE"] },
{ id: 'ANDVA15', name: "ANDINA DEL VALLE DESECHABLE x 6 unidades", price: 6540, category: "BEBIDAS", image: "catalogo productos/catalogoactual/packjugo1.5.png", flavors: ["DURAZNO", "TUTIFRUTILLA", "NARANJA", "PIÑA", "DAMASCO"] },
{ id: 'BEN5', name: "BENEDICTINO 500ML x 12 unidades", price: 4680, category: "AGUA", image: "catalogo/BENEDICTINO 500ML.png", flavors: ["CON GAS", "SIN GAS"] },
{ id: 'BEN3', name: "BENEDICTINO 3LT x 6 unidades", price: 6900, category: "AGUA", image: "catalogo/BENECDITINO 3LT.png", flavors: ["CON GAS", "SIN GAS"] },
{ id: 'BOMB200', name: "BOMBILLIN 200CC X24", price: 6480, category: "BEBIDAS", image: "catalogo productos/catalogoactual/bombillinpack.webp", flavors: ["DURAZNO", "PIÑA", "NARANJA", "MULTIFRUTILLA", "MANZANA"] },
{ id: 'JAL', name: "JUGO ANDINA 340ML X 6UNID", price: 3900, category: "BEBIDAS", image: "catalogo productos/catalogoactual/jugo340pack.png", flavors: ["DURAZNO", "PERA"] },
{ id: 'LATAC', name: "COCA COLA LATA 350 ML x 6 unidades", price: 4428, category: "BEBIDAS", image: "coca lata - copia.png", flavors: ["COCA COLA", "COCA COLA ZERO", "FANTA", "SPRITE", "INCA COLA"] },
{ id: 'MINIC', name: "LATA MINI 200ML 6 UNIDAD", price: 3330, category: "BEBIDAS", image: "catalogo productos/catalogoactual/lataminipack.webp", flavors: ["COCA COLA", "COCA COLA ZERO", "FANTA", "SPRITE"] },
{ id: 'MONSO6', name: "MONSTER 473ML X6 UNID.", price: 8238, category: "ENERGÃ‰TICAS", image: "catalogo productos/catalogoactual/monsterpack.webp", flavors: ["MANGO LOCO", "PIPERLINE PUNSH", "ZERO ULTRA", "ULTRA PARADISE", "ORIGINAL", "ORIGINAL ZERO", "RIPPER"] },
{ id: 'POWA1', name: "POWERADE 1.1LT x 6 unidades", price: 7550, category: "BEBIDAS", image: "catalogo productos/catalogoactual/powerpack.jpg", flavors: ["AZUL", "ROJO", "NARANJA"] },
{ id: 'VIT330', name: "VITAL 330 ML VIDRIO X 12UNID.", price: 8280, category: "AGUA", image: "catalogo/VITAL 330 ML VIDRIO X 12UNID..webp", flavors: ["CON GAS", "SIN GAS"] },
{ id: 'VITP', name: "VITAL 1LT x 6 unidades", price: 4750, category: "AGUA", image: "catalogo/VITAL 1LT.webp", flavors: ["SIN GAS"] },
{ id: 'VITSG16', name: "VITAL 1.6LT", price: 4866, category: "AGUA", image: "catalogo/VITAL 1.6LT.webp", flavors: ["CON GAS", "SIN GAS"] },
{ id: 'VITSG600', name: "VITAL 600ML", price: 5940, category: "AGUA", image: "catalogo/VITAL 600ML.png", flavors: ["CON GAS", "SIN GAS"] },
{ id: 'ALOEO', name: "ALOE VERA 500ML X CAJA", price: 17952, category: "BEBIDAS", image: "catalogo/ALOE VERA 500ML X CAJA.webp", flavors: ["ORIGINAL", "PIÑA", "FRUTILLA", "MANGO", "DURAZNO", "GRANADA", "COCO"] },
{ id: 'ENER250', name: "SCORE ENERGY DRINK 250 ML x 16 unidades", price: 13000, category: "ENERGÃ‰TICAS", image: "catalogo productos/catalogoactual/score500mlpack.jpg", flavors: ["ORIGINAL", "SANDIA", "FRUTOS TROPICALES"] },
{ id: 'ENERGY', name: "SCORE ENERGY DRINK 500 ML x 24 unidades", price: 18000, category: "ENERGÃ‰TICAS", image: "catalogo productos/catalogoactual/scorepack.webp", flavors: ["ORIGINAL", "SANDIA", "FRUTOS TROPICALES"] },
{ id: 'FR2', name: "Fruna 2.0 LT x 6 unidades", price: 3490, category: "BEBIDAS", image: "catalogo/Fruna 2.0 LT.jpg", flavors: ["COLA", "PIÑA", "PAPAYA", "NARANJA", "LIMON SODA", "FRUTAL", "GINGER ALE"] },
{ id: 'FR500', name: "Fruna 500ml x 12 unidades", price: 3590, category: "BEBIDAS", image: "catalogo productos/catalogoactual/fruna500mlpack.webp", flavors: ["COLA", "PIÑA", "PAPAYA", "NARANJA", "LIMON SODA", "FRUTAL", "GINGER ALE"] },
{ id: 'SCOREG', name: "SCORE 473ML x 24 unidades", price: 19680, category: "ENERGÃ‰TICAS", image: "catalogo productos/catalogoactual/scorepack2.jpg", flavors: ["GORILLA", "FRUIT PUNSH", "MANGO", "MOJITO", "BUBLE GUM", "ORIGINAL", "WATER MELON", "RADICAL WHILE"] },
{ id: 'SOPA', name: "SOPA MOLINOVA 94G X CAJA", price: 9000, category: "BEBIDAS", image: "catalogo/SOPA MOLINOVA 94G X CAJA.webp", flavors: ["POLLO", "CARNE", "CARNE PICANTE", "CAMARON"] },
{ id: 'KFE', name: "CAFE HELADO NESCAFE X 6 UNID.", price: 9300, category: "BEBIDAS", image: "catalogo/CAFE HELADO NESCAFE X 6 UNID..webp", flavors: ["LATE", "MOCKA", "ORIGINAL"] },
{ id: 'CRISLT', name: "CRISTAL LATA 470CC", price: 16560, category: "CERVEZA", image: "catalogo/CRISTAL LATA 470CC.webp" },
{ id: 'CRIS12', name: "CRISTAL LATA 470cc X12UNID", price: 8520, category: "CERVEZA", image: "catalogo/CRISTAL LATA 470cc X12UNID.webp" },
{ id: 'PISAL', name: "PISCO ALTO DEL CARMEN 1LT", price: 6400, category: "LICORES", image: "catalogo/PISCO ALTO DEL CARMEN 1LT.webp" },
{ id: 'WHISBUCH', name: "WHISKY BUCHANANS DELUXE 750 CC", price: 24230, category: "LICORES", image: "catalogo/WHISKY BUCHANANS DELUXE 750 CC.webp" },
{ id: 'WHISSAND', name: "WHISKY SANDY MAC 1LT", price: 12500, category: "LICORES", image: "catalogo/WHISKY SANDY MAC 1LT.webp" },
{ id: 'WHISGOLD', name: "WHISKY JW GOLD LABEL 750 ml - Copa", price: 56000, category: "LICORES", image: "catalogo/WHISKY JW GOLD LABEL 750 ml - Copa.webp" },
{ id: 'WHISBLACK', name: "WHISKY JW BLACK 750 ml - BLACK 200ML", price: 28990, category: "LICORES", image: "catalogo/WHISKY JW BLACK 750 ml - BLACK 200ML.webp" },
{ id: 'VINCAR', name: "VINO FLORESTA CAR 13.3g 750cc", price: 15800, category: "BEBIDAS", image: "catalogo/VINO FLORESTA CAR 13.3g 750cc.webp" },
{ id: 'VINCHARDONNAY', name: "VINO FLORESTA CHARDONNAY 13.4g 750CC", price: 16200, category: "BEBIDAS", image: "catalogo/VINO FLORESTA CHARDONNAY 13.4g 750CC.webp" },
{ id: 'VINREAL', name: "VINO M. REAL RVA X2 CS-MER 13.5G 750CC", price: 7170, category: "BEBIDAS", image: "catalogo/VINO M. REAL RVA X2 CS-MER 13.5G 750CC.avif" },
{ id: 'ESPAMAR', name: "ESPUMANTE AMARANTA BRUT 12.4g 750", price: 4650, category: "LICORES", image: "catalogo/ESPUMANTE AMARANTA BRUT 12.4g 750.png" },
{ id: 'AND125DES', name: "SPRITE 1.25 DESECHABLE x 6 unidades", price: 5340, category: "BEBIDAS", image: "catalogo/SPRITE 1.25 DESECHABLE.webp" },
{ id: 'ESPCARM', name: "ESPUMANTE CARMEN FK MOSCATO 12g 250", price: 20262, category: "LICORES", image: "catalogo/ESPUMANTE CARMEN FK MOSCATO 12g 250.png" },
{ id: 'VINMED', name: "VINO 120 3 MEDLLA L.HARVEST 12g 750 X3 UNID", price: 12800, category: "BEBIDAS", image: "catalogo/VINO 120 3 MEDALLA L.HARVEST 12g 750 X3 UNID.webp" },
{ id: 'VMREAL', name: "VINO CARM FK/MREAL CS 13.5g 750 X 3 UNID", price: 12680, category: "BEBIDAS", image: "catalogo/VINO CARM FK 750 X 3 UNID.png" },
{ id: 'VIN120M', name: "VINO 120 1.5 LT X6 UNID", price: 18624, category: "BEBIDAS", image: "catalogo/VINO 120 1.5 LT X6 UNID.jpg" },
{ id: 'MAL355', name: "MALTIN 355 ML X 24 UNIDAD", price: 27600, category: "BEBIDAS", image: "catalogo/MALTIN 355 ML X 24 UNIDAD.webp" },
{ id: 'WHISHOR', name: "WHISKY WHITE HOR 750 cc 40G X1", price: 7396, category: "LICORES", image: "catalogo/WHISKY WHITE HOR 750 cc 40G X1.webp" },
{ id: 'GINGORD', name: "GIN GORDONS 750 cc", price: 11650, category: "LICORES", image: "catalogo/GIN GORDONS 750 cc.webp" },
{ id: 'TQRAYSEVI', name: "GIN TANQUERAY SEVI 700 cc", price: 16920, category: "LICORES", image: "catalogo/GIN TANQUERAY SEVI 700 cc.webp" },
{ id: 'TQRAYROY', name: "GIN TANQUERAY ROYALE 700cc", price: 16920, category: "CERVEZA", image: "catalogo/GIN TANQUERAY ROYALE 700cc.webp" },
{ id: 'TQRAYBOS', name: "GIN TANQUERAY BOSSA NOVA 700cc", price: 16920, category: "LICORES", image: "catalogo/GIN TANQUERAY BOSSA NOVA 700cc.webp" },
{ id: 'RONANE', name: "RON MADDERO DORADO 750 cc", price: 4990, category: "LICORES", image: "catalogo/RON MADDERO DORADO 750 cc.webp" },
{ id: 'RONANEJ', name: "RON MADDERO ANEJO 750 cc", price: 6250, category: "LICORES", image: "catalogo/RON MADDERO ANEJO 750 cc.webp" },
{ id: 'RONBL', name: "RON MADDERO BLANCO 750 cc", price: 4550, category: "LICORES", image: "catalogo/RON MADDERO BLANCO 750 cc.webp" },
{ id: 'RONDOR1', name: "RON MADDERO DORADO 1LT", price: 5190, category: "LICORES", image: "catalogo/RON MADDERO DORADO 1LT.webp" },
{ id: 'BAV470', name: "BAVARIA 470 ML X24 UNID", price: 12240, category: "CERVEZA", image: "catalogo/BAVARIA 470 ML X24 UNID.webp" },
{ id: 'CCU125DES', name: "CCU 1.25 DESECHABLE", price: 5760, category: "BEBIDAS", image: "limonccu1.25.webp", flavors: ["KEM", "LIMON", "BILZ", "PAP", "PEPSI", "PEPSI ZERO"] },
{ id: 'COR330', name: "CORONA 330ML X18 UNID", price: 14850, category: "CERVEZA", image: "catalogo/CORONA 330ML X18 UNID.webp" },
{ id: 'COR620', name: "CORONA 620CC X12 UNID", price: 13090, category: "CERVEZA", image: "catalogo/CORONA 620CC X12 UNID.avif" },
{ id: 'ESC710', name: "LATA ESCUDO 710ML X 24 UNID", price: 18960, category: "CERVEZA", image: "catalogo/LATA ESCUDO 710ML X 24 UNID.webp" },
{ id: 'ICE275', name: "COCTEL CAPEL ICE 275 ML X 24", price: 19000, category: "LICORES", image: "catalogo/COCTEL CAPEL ICE 275 ML X 24.png", flavors: ["SANDIA", "MOJITO", "BERRIE", "MANZANA"] },
{ id: 'IRON', name: "ISOTONICA IRONADE 1LT", price: 4500, category: "LICORES", image: "catalogo/ISOTONICA IRONADE 1LT.jpg", flavors: ["ROJO", "AZUL", "NARANJA"] },
{ id: 'JC2', name: "JUGO CYRO 2LT x 6 unidades", price: 4250, category: "BEBIDAS", image: "catalogo productos/catalogoactual/cyro.webp", flavors: ["PIÑA", "NARANJA", "FRUTILLA", "DURAZNO"] },
{ id: 'JUMEXM', name: "JUMEX 355 X BANDEJA x 24 unidades", price: 15650, category: "BEBIDAS", image: "catalogo productos/catalogoactual/jumex pack.webp", flavors: ["PIÑA", "PIÑA COCO", "MANGO", "DURAZNO", "PERA", "MANZANA"] },
{ id: 'KAPOF', name: "KAPO X24 UNID", price: 5800, category: "BEBIDAS", image: "catalogo/KAPO X24 UNID.webp", flavors: ["PIÑA", "MANZANA", "FRAMBUESA", "NARANJA"] },
{ id: 'LIFE3', name: "AGUA LIFE 3 LT x 6 unidades", price: 3590, category: "AGUA", image: "purelife.webp", flavors: ["CON GAS", "SIN GAS"] },
{ id: 'LIN', name: "ENCENDEDOR LIN", price: 2100, category: "BEBIDAS", image: "catalogo/ENCENDEDOR LIN.webp" },
{ id: 'ROY470', name: "ROYAL 470 X 24 UNID", price: 18960, category: "CERVEZA", image: "catalogo/ROYAL 470 X 24 UNID.webp" },
{ id: 'SOL650', name: "SOL 650", price: 12000, category: "CERVEZA", image: "catalogo/SOL 650.webp" },
{ id: 'SX', name: "SUEROX 630ML SURTIDO", price: 17880, category: "BEBIDAS", image: "catalogo/SUEROX 630ML SURTIDO.webp", flavors: ["SURTIDO"] },
{ id: 'SXF', name: "FASTYLE 630ML X 6UNID", price: 7900, category: "BEBIDAS", image: "catalogo/FASTYLE 630ML X 6UNID.jpg", flavors: ["TROPICAL BLUE", "FRUTILLA", "FRUTILLA KIWI"] },
{ id: 'ZO', name: "ENERGY ZOOM 473 ML x 24 unidades", price: 15600, category: "ENERGÃ‰TICAS", image: "catalogo/ENERGY ZOOM 473 ML.png", flavors: ["ZOOM PURPLE", "ZOOM WHITE"] },
{ id: 'WHISRED', name: "WHISKY RED LABEL 750 CC", price: 9990, category: "LICORES", image: "catalogo/WHISKY RED LABEL 750 CC.webp" },
{ id: 'WHISKEY', name: "WHISKY JACK DANIEL 50ML", price: 2600, category: "LICORES", image: "catalogo/WHISKY JACK DANIEL 50ML.png" },
{ id: 'EXP500', name: "EXPORTACION VINO 500ML", price: 14768, category: "BEBIDAS", image: "catalogo/EXPORTACION VINO 500ML.webp" },
{ id: 'TQRAYLOND', name: "GIN TANQUERAY LON D 700CC", price: 15690, category: "LICORES", image: "catalogo/GIN TANQUERAY LON D 700CC.webp" },
{ id: 'ARROZ', name: "ARROZ MANGA 10 UNID", price: 6950, category: "BEBIDAS", image: "arrozelgrande.jpg", flavors: ["2GRADO"] },
{ id: 'HEX', name: "HUEVO EXTRA", price: 36000, category: "BEBIDAS", image: "catalogo/HUEVO EXTRA.webp" },
{ id: 'H1', name: "HUEVO 1ERA", price: 32000, category: "BEBIDAS", image: "catalogo/HUEVO 1ERA.png" },
{ id: 'JABAMIX', name: "JABA MIXTA 10 BEBIDAS", price: 10250, category: "PROMOCIONES", image: "catalogo/JABA MIXTA.jpg", isCustom: true },
{ id: 'NEST15', name: "AGUA MINERAL NESTLE PURE LIFE 1.5L", price: 1500, category: "AGUA", image: "catalogo/NESTLE PURE LIFE 1.5L.jpg" },
{ id: 'ANDMULTI', name: "ANDINA DEL VALLE MULTI-FRUTILLA 1.5L", price: 1800, category: "BEBIDAS", image: "catalogo/ANDINA DEL VALLE MULTI-FRUTILLA 1.5L.jpg" },
{ id: 'ANDPACK', name: "ANDINA DEL VALLE PACK SURTIDO", price: 4500, category: "BEBIDAS", image: "catalogo/ANDINA DEL VALLE PACK SURTIDO.jpg" },
{ id: 'ANDMANLATA', name: "ANDINA DEL VALLE MANZANA LATA 340ML X6", price: 4200, category: "BEBIDAS", image: "catalogo/ANDINA DEL VALLE MANZANA LATA 340ML X6.jpg" }
];
